version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.Dockerfile
      context: ./Nginx
    volumes:
      - ./Nginx/logs:/var/log/nginx
    ports:
      - "8080:8080"

  node-back:
    build:
      context: ./NodeBack
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./NodeBack:/usr/app
    command: ["npm", "run" , "dev"]
